"""
train_model.py - trains the 16-8-3 MLP used by TRACE-X's hand-written
forward pass (include/model.h). Regenerates include/model_weights.h.

Uses only numpy - no TensorFlow needed. Run with: python3 train_model.py

The synthetic spectra generated here mirror generateSpectrum() in
src/main.cpp exactly (same zones, same peak centers/widths/amplitudes,
same baseline and jitter ranges). If you change the peak parameters in
generateSpectrum(), mirror those changes here too, or the firmware will
be feeding the model data outside its trained distribution.
"""

import numpy as np

INPUT_SIZE = 16
HIDDEN_SIZE = 8
OUTPUT_SIZE = 3

CLEAR, NARCOTIC, EXPLOSIVE = 0, 1, 2


def gaussian_peak(x, center, width, amp):
    d = (x - center) / width
    return amp * np.exp(-0.5 * d * d)


def generate_spectrum(zone, rng):
    """Mirrors generateSpectrum() in src/main.cpp."""
    x = np.arange(INPUT_SIZE, dtype=np.float64)

    # baseline = 0.05 + random(-15,15)/1000, clamped >= 0
    baseline = 0.05 + rng.uniform(-0.015, 0.015, size=INPUT_SIZE)
    spectrum = np.clip(baseline, 0, None)

    # jitter = random(-30,30)/100
    jitter = rng.uniform(-0.3, 0.3)

    if zone == CLEAR:
        pass  # baseline only, no peak
    elif zone == NARCOTIC:
        # one peak near bin 4
        center = 4.0 + jitter
        amp = 0.75 + rng.uniform(-0.06, 0.06)
        spectrum = spectrum + gaussian_peak(x, center, 1.4, amp)
    else:
        # EXPLOSIVE - peak near bin 11 plus smaller peak near bin 14
        center1 = 11.0 + jitter
        amp1 = 0.85 + rng.uniform(-0.06, 0.06)
        center2 = 14.0 + jitter
        amp2 = 0.45 + rng.uniform(-0.05, 0.05)
        spectrum = spectrum + gaussian_peak(x, center1, 1.1, amp1)
        spectrum = spectrum + gaussian_peak(x, center2, 0.9, amp2)

    return np.clip(spectrum, 0.0, 1.0)


def make_dataset(n_per_class, rng):
    X, y = [], []
    for zone in (CLEAR, NARCOTIC, EXPLOSIVE):
        for _ in range(n_per_class):
            X.append(generate_spectrum(zone, rng))
            y.append(zone)
    X = np.array(X, dtype=np.float64)
    y = np.array(y, dtype=np.int64)
    idx = rng.permutation(len(X))
    return X[idx], y[idx]


def one_hot(y, n_classes):
    out = np.zeros((len(y), n_classes))
    out[np.arange(len(y)), y] = 1.0
    return out


def train(X, y, hidden=HIDDEN_SIZE, epochs=3000, lr=0.05, seed=0):
    rng = np.random.default_rng(seed)
    n_in, n_out = X.shape[1], OUTPUT_SIZE

    W1 = rng.normal(0, 0.5, size=(n_in, hidden))
    b1 = np.zeros(hidden)
    W2 = rng.normal(0, 0.5, size=(hidden, n_out))
    b2 = np.zeros(n_out)

    Y = one_hot(y, n_out)
    n = len(X)

    for epoch in range(epochs):
        # forward
        z1 = X @ W1 + b1
        a1 = np.maximum(z1, 0)  # ReLU
        z2 = a1 @ W2 + b2
        z2_shifted = z2 - z2.max(axis=1, keepdims=True)
        exp = np.exp(z2_shifted)
        probs = exp / exp.sum(axis=1, keepdims=True)

        # backward (softmax + cross-entropy gradient)
        dz2 = (probs - Y) / n
        dW2 = a1.T @ dz2
        db2 = dz2.sum(axis=0)
        da1 = dz2 @ W2.T
        dz1 = da1 * (z1 > 0)
        dW1 = X.T @ dz1
        db1 = dz1.sum(axis=0)

        W1 -= lr * dW1
        b1 -= lr * db1
        W2 -= lr * dW2
        b2 -= lr * db2

        if epoch % 500 == 0 or epoch == epochs - 1:
            preds = probs.argmax(axis=1)
            acc = (preds == y).mean()
            loss = -np.log(probs[np.arange(n), y] + 1e-9).mean()
            print(f"epoch {epoch:5d}  loss {loss:.4f}  train acc {acc*100:.1f}%")

    return W1, b1, W2, b2


def evaluate(W1, b1, W2, b2, X, y):
    z1 = X @ W1 + b1
    a1 = np.maximum(z1, 0)
    z2 = a1 @ W2 + b2
    preds = z2.argmax(axis=1)
    return (preds == y).mean()


def write_header(path, W1, b1, W2, b2, train_acc, test_acc):
    with open(path, "w") as f:
        f.write("// Auto-generated by train_model.py - do not edit by hand.\n")
        f.write("// Tiny 16-8-3 MLP trained on synthetic spectral data.\n")
        f.write(f"// Train accuracy: {train_acc*100:.1f}%  Test accuracy: {test_acc*100:.1f}%\n")
        f.write("#pragma once\n\n")
        f.write(f"#define MODEL_INPUT_SIZE {INPUT_SIZE}\n")
        f.write(f"#define MODEL_HIDDEN_SIZE {HIDDEN_SIZE}\n")
        f.write(f"#define MODEL_OUTPUT_SIZE {OUTPUT_SIZE}\n\n")

        f.write(f"const float MODEL_W1[{INPUT_SIZE}][{HIDDEN_SIZE}] = {{\n")
        for row in W1:
            f.write("  { " + ", ".join(f"{v:.6f}f" for v in row) + " },\n")
        f.write("};\n\n")

        f.write(f"const float MODEL_B1[{HIDDEN_SIZE}] = {{ ")
        f.write(", ".join(f"{v:.6f}f" for v in b1))
        f.write(" };\n\n")

        f.write(f"const float MODEL_W2[{HIDDEN_SIZE}][{OUTPUT_SIZE}] = {{\n")
        for row in W2:
            f.write("  { " + ", ".join(f"{v:.6f}f" for v in row) + " },\n")
        f.write("};\n\n")

        f.write(f"const float MODEL_B2[{OUTPUT_SIZE}] = {{ ")
        f.write(", ".join(f"{v:.6f}f" for v in b2))
        f.write(" };\n")


def main():
    rng = np.random.default_rng(42)
    X_train, y_train = make_dataset(n_per_class=500, rng=rng)
    X_test, y_test = make_dataset(n_per_class=100, rng=rng)

    W1, b1, W2, b2 = train(X_train, y_train)

    train_acc = evaluate(W1, b1, W2, b2, X_train, y_train)
    test_acc = evaluate(W1, b1, W2, b2, X_test, y_test)
    print(f"\nFinal train accuracy: {train_acc*100:.1f}%")
    print(f"Final test accuracy:  {test_acc*100:.1f}%")

    write_header("model_weights.h", W1, b1, W2, b2, train_acc, test_acc)
    print("\nWrote model_weights.h - copy it into include/model_weights.h")


if __name__ == "__main__":
    main()